name: Cross Building
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    paths:
      - 'src/**'

jobs:
  build:
    strategy:
      fail-fast: false # Keep other jobs running even if one fails
      matrix:
        # Environments here
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: windows-latest
            compiler: msvc
            experimental: true
          - os: macos-latest
            compiler: clang

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental || false }}

    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Configure
        # This uses the compiler from the matrix to tell xmake what to do
        run: xmake f --toolchain=${{ matrix.compiler }} -m release -y

      - name: Build
        run: xmake

